{
    'name': 'Css',
    'version': '19.0.1.0.0',
    'summary': 'Accessories and product',
    'sequence': -100,
    'description': """ product """,
    'category': 'Productivity',
    'website': 'https://www.odoomates.tech',
    'depends': ['base','account','account_reports','accountant','account_batch_payment','purchase','analytic','contacts','account_followup','account_accountant_batch_payment'],
    'license': 'LGPL-3',
    'application': True,
    'data': [
        'security/ir.model.access.csv',
        'security/security.xml',
             'views/accounts.xml',
             'views/contact.xml',
             'views/contact_report.xml',
             'views/payment_report.xml',
             # 'views/res_setting_view.xml',
             'reports/css_tax_invoice_report.xml',
             'reports/css_tax_invoice_report_with_discount.xml',
             'reports/css_tax_invoice_report_with_shipto.xml',
             'reports/css_tax_invoice_report_without_logo.xml',
             'reports/material_invoice.xml',
             'reports/material_invoice_without_logo.xml',
             'reports/custom_bank_format.xml',
             'reports/purchase_report_with_logo.xml',
             'reports/purchase_report_without_logo.xml',
             'wizard/import_pmt.xml',
             'wizard/reason_wizard.xml',
             'wizard/send_to_checker.xml',
             'wizard/import_contact_bank.xml',
             'reports/missing_data.xml',
             'reports/journal_voucher.xml',
             'views/account.xml',
             ],
    'website': 'https://planet-odoo.com/',
    'installable': True,
    'auto_install': False,

}